services:
  cockroachdb:
    image: cockroachdb/cockroach:latest
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    environment:
      - COCKROACH_DB=stockwise
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    healthcheck:
      test: ["CMD", "cockroach", "node", "status", "--insecure"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=cockroachdb
      - DB_PORT=26257
      - DB_USER=root
      - DB_NAME=stockwise
      - DB_SSLMODE=disable
    depends_on:
      - cockroachdb
    restart: unless-stopped
    volumes:
      - ./backend:/app
    command: ["go", "run", "main.go"]

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./frontend/stockwise:/app/stockwise
      - /app/stockwise/node_modules

volumes:
  cockroach-data: 