services:
  cockroachdb:
    image: cockroachdb/cockroach:v23.1.11
    command: start-single-node --insecure
    ports:
      - "26257:26257"
      - "8080:8080"
    volumes:
      - cockroach-data:/cockroach/cockroach-data
    restart: unless-stopped

  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=cockroachdb
      - DB_PORT=26257
      - DB_USER=root
      - DB_NAME=stockwise
    depends_on:
      - cockroachdb
    restart: unless-stopped
    command: ["./main"]

  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    restart: unless-stopped
    volumes:
      - ./frontend/stockwise:/app/stockwise
      - /app/stockwise/node_modules

volumes:
  cockroach-data: 